### ISSUE TITLE
Why are the DST coords divided by 10?

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#10]
p.addStitchRel(x / 10.0, y / 10.0, flags, true);

It's causing the statistics to fubar. Generally since the coords are integers within 1/10th of a mm, you could multiply them by 10 to make them a mm. But typically one allows them to remain the same and understand that 1/10th mm is equal to a pixel?

**Comment by JoshVarga** [comment]
This has been updated
