### ISSUE TITLE
What's with the line width based on scale?

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#11]
_paint.setStrokeWidth(scale/9.0f);

If you don't set a stroke width in android the lines end up being 1 pixel wide regardless how much you zoom. If the coord system is 1 px = 1/10 mm then typically your thread is going to be 3 wide (though there are different threads of different diameters than 30 pt). Apparently since the end of the DST parsing divides the X and Y by 10, we'd be 1 px = 1/100 mm. So at a 1/1 zoom factor we'd be looking at a stroke width of 1/900 ?

**Comment by tatarize** [comment]
I fixed the scale, now you can really see how weird it is.

https://youtu.be/pFOGzsmKJFY

**Comment by JoshVarga** [comment]
Yeah you are correct, that does look crazy. I set the stroke width to 0.1 for now. Seems to function much better. It is no longer based on scale.
