### ISSUE TITLE
How should set colors work?

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#15]
It is not too hard to add a color change view or change the colors in the pattern, and given the few remaining requirements. How should this work? Fragment? In view selection? Tool? Series of alert dialogs? The simple ability to do this, is easy. How should the design work?

**Comment by JoshVarga** [comment]
I like the way they do it on DST Viewer Pro (https://play.google.com/store/apps/details?id=com.faya.dstreader&hl=en). There are plenty of color picker options, for example (https://android-arsenal.com/tag/18) Choosing the colors at the statistics/properties/details or as a separate tool would be intuitive enough.

**Comment by tatarize** [comment]
Updated the color property, tool, thing as a fragment. Just does random color each time it is pressed though. Basically set it up to be better than DST Viewer Pro. I don't have any idea how they screwed up the refresh of that stuff so badly. But, they build a bitmap each time something changes and might even do so for the items in the ListView too. The proper way is a subclassed pattern in the ListView:
https://www.bignerdranch.com/blog/customizing-android-listview-rows-subclassing/ which is how I have it set. It's a bit odd, but lets you use XML for the individual items.

**Comment by valonsejdini** [comment]
Added a colour picker.
