### ISSUE TITLE
More realistic embroidery view

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#17]
As an option? Or primarily? Are we talking thread texture on the lines, or something like thread width 3.0 for 30pt thread? And an option for no thread width? (No, thread width does one pixel wide at all zooms, so zoom in does bones/line view)

**Comment by JoshVarga** [comment]
I was thinking of thread texture on lines, along with more accurate thread width (potentially based on selected thread type).

**Comment by tatarize** [comment]
fabricocouto's update routine in #95 suffices to complete this enhancement. It actually looks quite nice.
