### ISSUE TITLE
Save any changes to DST format

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#18]
Why dst? They waste 512 bytes. They don't store colors. They aren't open source. Surely something like explicitly colored polyline svgs (the kind Embroidery offer can open might be more versatile.)

**Comment by JoshVarga** [comment]
With the most recent commit I added the ability to save to DST (still has a color change bug), EXP, PEC and PES. Like you mentioned in another issue it would be nice to have for support for a phone plugged in via USB to the embroidery machine.
