### ISSUE TITLE
Nothing to switch on or off fragments, or various tools.

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#21]
```
    @Override
    public void onBackPressed() {
        if (tryCloseFragment(ColorStitchBlockFragment.TAG)) {
            return;
        }
        super.onBackPressed();
    }

```

Adding that to the MainActivity will make it so that the ColorStitchBlockFragment is closed when you press back, and if already closed will exit (consistent with Android best practices (some amount of hitting back should exit)).

But, there's no way to turn on or off fragments to display various bits of information etc. Or any any idea how such a thing would happen, or if it needs to. But, mobile screens are small, and if you want to use several things like compare the size of the image to a given hoop size, you would need some place to select the hoop. Or if you wanted to break the Pattern apart and look at each section individually, you would need to be able call up a different fragment as such.

**Comment by JoshVarga** [comment]
I think for future work we should probably try to put these tool settings/selection in a Material design layout using slide out menus like the following link.

https://material.google.com/patterns/navigation-drawer.html#navigation-drawer-specs

Your thoughts?

**Comment by tatarize** [comment]
You can use navigation drawers, they totally work and look sort of nice. In Touch Embroidery, I use a drawer for the various layers, and each layer has a thumbnail, and some basic data about that layer, and things can be rearranged. 

You only have so much screen space, and the way it's setup currently sort of takes a lot of that space. And when you close the fragment, there's no way to get it back. Though, at present, other than statistics, and colors currently it doesn't have any other information.

Though if the whole thumbnail of the embroidery thing in part 2 were done up, such that there was a database of embroidery works, that one could have a fragment for that, that would  work for a drawer.

Though it very likely would be better as a different activity. Especially a PICK intent looking for an embroidery file, and just use that like a gallery. Save embroidery objects to it, get them back out of it, and a nice view of the embroidery library. Especially if it saved the files out too. So you could do whatever that "Embrotailer lite" thing was trying to do, but much better in that you could save a library of embroidery to the activity and convert it to PES and upload it directly to somebody's embroidery machine.

I wrote an Android Vector Icon Drawer, called DAVID: Android Vector Icon Draw, that includes a library a bit like that. Where it simply has something that responds to a PICK intent, allowing you to send out the request, then loads up the Library activity, allows you to select requires icon svg, and loads that up. -- But, because it's done via an intent, anything that requests a file like that can use the same library. (I can pick them from Touch Embroidery just as easily as from the icon drawer). --- So really other recently viewed files such things might not require their own fragment.

Sure, I guess. I could toss that into a drawer, in pretty short order. And we can always switch out the fragments in the drawers.

**Comment by JoshVarga** [comment]
Implemented
