### ISSUE TITLE
Needs Google Play Release

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#22]
Version 1 is done. The doable parts of version 2 finished, though that sample embroidery selection thing is totally doable and would be like a Pick library and save to library locally. But, it needs a proper google play release. If memory serves it's 25 bucks and you don't need the merchant account if you aren't selling anything.

**Comment by tatarize** [comment]
Seriously, outside of my own app, Touch Embroidery (and it doesn't even load anymore than DST and SVG (though there's all this nice MIT code)), this blows most of the other stuff out of the water. I was shocked to notice that there's apparently water. DST Viewer Pro, got pullled and reuploaded, now they want 3 bucks. And whatever that PES uploader thing did, before it couldn't even view the images. But, seriously, it would be very few tweaks to do that, but have it load from everywhich format. Maybe even have a pro version for money.

**Comment by JoshVarga** [comment]
I think at this point I would like to update two things then I will pay for an Embroidermodder Google Play account.
1) The color picker to not be random
2) Comment out the histogram portion (stitch count by length) of the properties (mainly because we would need a histogram viewer to make it look nice.

Other than that I agree everything looks really good, and ready for an initial release.

**Comment by JoshVarga** [comment]
I cleaned up a few things locally, created a developer account and have put an alpha version out for our testing. We should be able to test by joining the tester group. You should be able to add yourself with the following link.

https://play.google.com/apps/testing/com.embroidermodder.embroideryviewer

Let me know what you think, we may be able to push a production version soon.

**Comment by tatarize** [comment]
It's not hard to draw a histogram. You want custom view that draws 10 slightly overlapping rectangles of different heights normalized into set space? -- Also, I'd go by the axiom that if you aren't embarrassed by the first release you released it too late.

**Comment by tatarize** [comment]
Wait, now I remember, it totally is hard to draw a histogram from scratch

https://youtu.be/WUQ8UmmNawc



       public void showStatistics() {
        AlertDialog.Builder builder = new AlertDialog.Builder(this);
        builder.setMessage(drawView.getStatistics());

        HistogramView h = new HistogramView(this);
        h.buildStitchHistogram(drawView.getPattern());
        builder.setView(h);

        builder.show();
    }

------


    package com.embroidermodder.embroideryviewer;

    import android.content.Context;
    import android.graphics.Canvas;
    import android.graphics.Color;
    import android.graphics.Paint;
    import android.graphics.RectF;
    import android.util.AttributeSet;
    import android.view.View;

    import java.util.ArrayList;

    public class HistogramView extends View {

    public Histogram chart;

    public HistogramView(Context context) {
        super(context);
        init();
    }

    public HistogramView(Context context, AttributeSet attrs) {
        super(context, attrs);
        init();
    }

    public HistogramView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init();
    }

    public void init() {
        chart = new Histogram();
    }

    @Override
    protected void onDraw(Canvas canvas) {
        chart.draw(canvas);
    }


    public Histogram buildStitchHistogram(Pattern pattern) {
        chart = new Histogram();
        float min = pattern.getMinStitch();
        float max = pattern.getMaxStitch();
        float start = min;
        float step = (max - min) / 10.0f;
        for (int i = 0; i < 10; i++) {
            float tmin = (i * step) + start;
            float tmax = ((i + 1) * step) + start;
            chart.addData(tmin,tmax,pattern.getCountRange(tmin, tmax));
        }
        chart.render();
        return chart;
    }



    public class Histogram {

        public ArrayList<DataValue> data;

        double min;
        double max;
        double highvalue;
        double lowvalue;

        Paint paintSolid;
        Paint paintOutline;
        Paint paintText;

        boolean dirty;

        double scalex;
        double scaley;


        public Histogram() {
            data = new ArrayList<>();
            paintSolid = new Paint();
            paintSolid.setColor(Color.BLUE);
            paintOutline = new Paint();
            paintOutline.setColor(Color.RED);
            paintOutline.setStyle(Paint.Style.STROKE);
            paintOutline.setStrokeWidth(10);
            paintText = new Paint();
            paintText.setTextSize(30);

            scalex = 1;
            scaley = 1;
            dirty = false;
        }

        public void addData(double start, double stop, double value) {
            data.add(new DataValue(start,stop,value));
            dirty = true;
        }


        public void render() {
            min = Double.POSITIVE_INFINITY;
            max = Double.NEGATIVE_INFINITY;
            highvalue = Double.NEGATIVE_INFINITY;
            lowvalue = Double.POSITIVE_INFINITY;
            for (DataValue d : data) {
                if (d.startValue < min) min = d.startValue;
                if (d.stopValue > max) max = d.stopValue;
                if (d.value < lowvalue) lowvalue= d.value;
                if (d.value > highvalue) highvalue = d.value;
            }

            scalex = (max - min);
            scalex *= 1.2;
            scalex = 1d/ scalex;

            scaley = (highvalue);
            scaley *= 1.2;
            scaley = 1d/scaley;

            dirty = false;
        }

        public void draw(Canvas canvas) {
            if (dirty) render();
            RectF rect = new RectF();
            for (DataValue datum : data) {
                rect.set((float)(canvas.getWidth() * datum.startValue * scalex), canvas.getHeight() - (float)(canvas.getHeight() * datum.value * scaley), (float)(canvas.getWidth() * datum.stopValue * scalex), canvas.getHeight());
                canvas.drawRect(rect, paintOutline);
                canvas.drawRect(rect, paintSolid);
                canvas.drawText("" + datum.value,rect.left,rect.top,paintText);
                canvas.drawText("" + datum.startValue,rect.left,rect.bottom,paintText);
            }
        }

        public class DataValue {
            double startValue;
            double stopValue;
            double value;

            public DataValue(double startValue, double stopValue, double value) {
                this.startValue = startValue;
                this.stopValue = stopValue;
                this.value = value;
            }
        }


    }

    }

**Comment by JoshVarga** [comment]
I agree about releasing the app, it isn't quite what we all would like but it seems to be better/ support more formats etc. than anything that is out there on Android right now. I will test a little, upload the current APK and set it for release. I will make an update here once it is released.

**Comment by JoshVarga** [comment]
I just released the app to the public. Hopefully we will get some good feedback.
