### ISSUE TITLE
Rotation of Screen Loses, replacement colors.

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#27]
Pretty basic. Change the color, turn the screen, color went back to the original.

**Comment by tatarize** [comment]
That won't fix it. It will simply redisplay the view in the rotated state without the shutdown and restore. Rather it should simply write all current embroidery to the bundle. After all this problem is going to crop back up if Android kills it for memory.  You can call .pack() on the PointList and get an array of floats. And you can save an array of floats to a bundle. Include the color of the layer, and iterate through the layers and that'd do it. Just telling it not to rebuild the view or kill the view totally makes it matter less, but it still matters.

**Comment by valonsejdini** [comment]
It seems to work fine, have you tried it ? Declaring android:configChanges="orientation|screenSize" will prevent the Activity from restarting and let the framework handle the rest, hence, leaving the state immutable. It is a simple solution which I think is ok for now.

**Comment by tatarize** [comment]
It would work for a while. And covers the rotation instances. I'd also toss in the keyboard thing (older model phones will reload on the pull-out of the physical keyboard). But, it would still lose that information if it got killed for memory or any of the other very good reasons it has for saving the state. It'll certainly work for like 95% of cases which is fine. But, actually writing the data to the bundle and reading it back out, is certainly preferred, and not remotely that hard to do. It would also, have some perfectly determinable effects like having the calculated _width and _height things wrong after a rotation and the matrix that figures the position will stay where it was set for the other configuration. -- But, sure most of the test cases it'll do pretty well.

**Comment by tatarize** [comment]
Properly fixed this. https://github.com/Embroidermodder/MobileViewer/pull/75

Actually saves the data to internal memory so it won't lose it even if you hard close the app. Removed the kludge.
