### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by JoshVarga** [Embroidermodder/MobileViewer#29]
What do you guys think of adding a splash screen? The app loads quickly now, and it is nice to go directly into what you want to do. I have noticed a large number of apps that have an initial splash screen though.

**Comment by tatarize** [comment]
Depends on the branding. Is there a strong need to have Embroidermodder presents, Embroidery Viewer or some such thing, to make people remember the stuff? It's fine marketing if marketing is what you want, rather pointless as they don't do anything other than marketing and brand awareness.

**Comment by JoshVarga** [comment]
I don't think we need marketing at this point, I was thinking of whether
the app would look more professional with a splash screen included.

**Comment by tatarize** [comment]
Apparently Google changed their position on this. Generally the rule is apparently that they are acceptable so long as they don't waste any time. And there is enough time on a cold start.

https://plus.google.com/+AndroidDevelopers/posts/Z1Wwainpjhd

Generally involved switching the theme at the start, then toggling it back. Which doesn't make them not pointless, but it does make them cost very little, in either space or user time. 

If you start the (without anything in tasks) app, you'll notice like a 200-300 ms of a white screen. The idea would let that be replaced with something else.

**Comment by tatarize** [comment]
Implemented the splash screen according to the way Google suggested. Loads with the main icon as such and a bit of a gradient thing, (can be changed, whenever) and only shows during the loadup. Simply replaces the white screen. No time loss or any issues as such.
