### ISSUE TITLE
IFormat.Writer

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#35]
What's the protocol here, just add an interface for IFormat.Writer that takes a outstream and a pattern for writing?

**Comment by JoshVarga** [comment]
I have initial code to write EXP, PEC, almost PES, and I will include DST then check in. As of right now I have the following signature....

```
    public interface Writer {
        void write(EmbPattern pattern, OutputStream stream);
    }
```
I will check in tonight most likely then we can review.

**Comment by tatarize** [comment]
Most of the exporting stuff is just pumping it into the right intent and how to send those intents. Though,  *EmbroTailor lite is saving to external media, namely the mnt usb device which is the embroidery machine. So it seems like writing to external media would also be wildly helpful. You could well open an .xxx file, then have it converted to PES and pushed out directly to a brother embroidery machine, all from your tablet. -- That's gotta be useful to a lot of people.

**Comment by JoshVarga** [comment]
I pushed new code to do almost exactly what you were mentioning, the code is incomplete and needs some cleanup but wanted to put it out there for you guys to take a look at and make suggestions. Specifically I wonder when we save how we should save, if we allow the user to choose a file name we can infer the file type. However if we allow the user to choose the directory this may not be visible to the embroidery machine. We potentially need both of these available within the app. 

If we eventually wanted this app or potentially another app to organize embroidery and view thumbnails we would want to be able to save to a (probably application specific) directory.

**Comment by tatarize** [comment]
Yeah, saving externally to the app itself (there's internal app space and external) is somewhat required for this. Apparently hooking the phone or whatnot to an embroidery machine on at least some modern Brother machines will let you access this data. I'm not sure it's directory specific as you can treat an android device like a USB device, but I'm unsure the specifics as I only have access to an old large swf single-head machine, rather than any of the smaller home devices people have. In any case it certainly would external to the app directory space. So we'll need to add:
```
 <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
 <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

In the manifest. Which matters much less Marshmallow+ given the permissions on the fly.

So at a minimum it should be able to take the file in whatever format, and export it via intents and/or save to external storage of a directory of the user's choice, in a given format.  This would allow a user to click a link and download an embroidery from say .xxx format and then load it in EV and save in PES format to the mounted usb directory. Then a click or two on the machine and you load it up from the phone. That or you could quickly and easily download the file from a webpage as such, then export it in say .DST as a send intent and attach that to a gmail or whatnot. 

Such things would be pretty in general. 

---

If the embroidery files were wanted in thumbnail views like a different app that either stored the files internally cached or generally created thumbnails on the fly (though I think most images would be larger than just most basic embroidery files), even though very few of them are compressed. (.emb comes to mind, if you ever have one of those there's some interesting files inside them if you get something like 7zip and uncompress them). But, if we were doing stuff external on the card anyway, it would be pretty straight-forward to create a quick thumbnail for them. The same draw code can simply be applied to a Bitmap and creates a thumbnail for them, though at that rate you could likely just cache the vector bits and the timestamp and use that. I'd have to suppose this is going to be really fast for most things.  In fact, it might not even need caching. Even at the extreme end I only produce DSTs with a like 120k stitches and that's pretty big. But, you can calculate the size is simply 512 + 3 * stitches so 360,512 or so.  And reading 300k is small fry.  So like 5 meg images fully rendered are done in 231k Like this ship image. 74k stitches. 

![firefly](https://cloud.githubusercontent.com/assets/3302478/17648804/9a6ea2ce-61d7-11e6-8c44-acd2f7bb6cab.png)

So really I have to suppose the correct answer is to simply draw the embroidery and not even to save a copy of it cached. Which would mean internal directory stuff wouldn't be needed at all, because the file would be all that matters. You could just have a directory on the device and save copies embroidery files there, or another copy to a different relevant directory if that's what they needed.

That would mean the other viewer could simply be built into the primary application. You could have a different activity that when used would just save the file to the correct directory. Then have a library built simply via putting a bunch of stuff in a directory full of stuff, and looking through thumbnails generated on the fly.

**Comment by tatarize** [comment]
Forgot I already added the read external because downloads often referred to files that were external rather than properly emulated.

**Comment by tatarize** [comment]
Tried it. Seems to work a bit. Odd effect. Needs to navigate directories though, I just have it make a list and make a view for each file and when you run into one that has a IFormat.Reader to load that up and view it. It's mostly blanks and a few working bits. Hit a 100k dst and it hit very heavy lag. So I guess it needs directory stuff to properly navigate, likely a gridview, and to load the files in a separate thread.  But the core bit totally works. It was like half a second lag at the bad end.

**Comment by tatarize** [comment]
Bit better implementation, posted about it in the more proper thread about thumbnail views.

More on topic for this thread, I'd suppose that we should likely support most of the ways to load and save files. To various subdirectories or from them externally or shared via an intent. And with all the typical stitch file formats.  Though, the more that is added the more the interface will suck without a good design minded person figuring out where things should go.

**Comment by tatarize** [comment]
The newest version has an emm format that is lossless for all embroidery formats I've encountered and pretty easy to expand. But, can save those files internally quite quickly, so if this was a thing somebody wanted to work with, it would be entirely possible now without much trouble at all.

https://github.com/Embroidermodder/MobileViewer/pull/75
