### ISSUE TITLE
PointList change for the checkBounds is in error.

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#40]
```
private boolean checkBounds(float px, float py) {
 -        boolean boundChanged = false;
          if (px < minX) {
              minX = px;
 -            boundChanged = true;
 +            return true;
          }
          if (px > maxX) {
              maxX = px;
 -            boundChanged = true;
 +            return true;
          }
          if (py < minY) {
              minY = py;
 -            boundChanged = true;
 +            return true;
          }
          if (py > maxY) {
              maxY = py;
 -            boundChanged = true;
 +            return true;
          }
 -        return boundChanged;
 +        return false;
      }
```

It is the case that if you check bounds which is outside the bounds for both x and y it must update both of these elements and then return true for the bound change. Otherwise it will desync.

If the pointlist bounds are between 0 and 50 and 0 and 100 and you add a new point at 200,200. It must update that the new maxX and new maxY are now 200 and 200. The code changed there will update the maxX then abort by returning true. Without updating the maxY. This will cause it to look like it has a clean set of bounds but actually have a false positive.

**Comment by JoshVarga** [comment]
I cleaned this up in the most recent commit. Since there is no use of the return value, I simply removed it for now. If we need it in the future it's easy to add back in.

**Comment by tatarize** [comment]
Yeah, I had some code to track the nearest point to a given point. Basically two sorted lists in the x and y coords, binary search into the list to the correct point in both lists and progressively move outward from the center in each of the 4 directions +x, +y, -x, -y until each of the four acceptable directions main component was greater than the currently held max (which implies even if the other distance was 0 it would still be farther in each of those directions, therefore the currently held max is the closest point). Getting a very nice and highly quick O(nlog(n)) search for the points. The points were then moved and resorted (which would involve very few swaps, and cheap inserts etc). I thought that code would help to know when the bounds were changed but really, since the bounds were accurately maintained I could just call getMaxX() or whatnot directly and let the datastructure know whether it's dirty or not. And didn't really need to know, because if it had clean bounds it would just give me the right data in O(1) anyway.

There's also excessbounds vs. dirtybounds. The former says the numbers are still good, but they might exceed the real value, because something removed something that might have been on the edge. And dirty suggests that no guarantees can be made with regard to the bounds. Which seemed really brilliant at the time and I totally implemented it properly, but I have never once found a reason I would want excessive bounds and every single call to computeBounds(boolean) is sent with true. Even distanceQuickFail(x,y) which returns a quick minimum distance that point must be away from the given layer. (If searching whether a point is some distance d from some point in the given layer, if it's already more than d away from the bound of that layer, there exists no point in that layer can be closer than d, by definition). As a quick pre-check before doing the more costly getIndexOfClosestPoint() on the pointlist.

It's a fantastic core datastructure, but sometimes doing really fast code for very specialized functions is a pain.

I have a PointSeries class that subclasses (with the overt understanding that this is a series of connected points) it and it has a function to divide up lines beyond a certain length into evenly spaced breaks. But, because declaring a new float array for the class would be expensive or n-loops it does it in 2 loops. One to figure out what the size will be and a second to do the action, keeping track of a particular index value.


    public int longSplit(double maxDistance, int index) {
        if (count <= 2) return index;
        double maxDistanceSq = maxDistance * maxDistance;
        double lineDistance;
        int splits = 0;

        float ex1 = pointlist[count - 2];
        float ey1 = pointlist[count - 1];
        float sx1, sy1;

        for (int pos = count - 2; pos > 1; pos -= 2) {
            sx1 = pointlist[pos - 2];
            sy1 = pointlist[pos - 1];
            lineDistance = distanceSq(sx1, sy1, ex1, ey1);
            if (lineDistance > maxDistanceSq) {
                lineDistance = Math.sqrt(lineDistance);
                int breaks1 = (int) (Math.ceil(lineDistance / maxDistance)) - 1;
                splits += breaks1;
            }
            ex1 = sx1;
            ey1 = sy1;
        }
        if (splits == 0) {
            return index;
        }

        int splitCount = (splits * 2) + count;
        ensureCapacity(splitCount);

        int writePos = splitCount;
        float ex = pointlist[count - 2];
        float ey = pointlist[count - 1];
        float sx, sy;

        int returnIndex = (writePos) >> 1;

        pointlist[writePos - 2] = ex;
        pointlist[writePos - 1] = ey;
        writePos -= 2;
        int relativeIndex = index << 1;

        for (int readPos = count - 2; readPos > 1; readPos -= 2) {
            if (readPos == relativeIndex) {
                returnIndex = (writePos) >> 1;
            }
            sx = pointlist[readPos - 2];
            sy = pointlist[readPos - 1];
            lineDistance = distanceSq(sx, sy, ex, ey);
            if (lineDistance > maxDistanceSq) {
                lineDistance = Math.sqrt(lineDistance);
                int breaks = (int) (Math.ceil(lineDistance / maxDistance)) - 1;

                float stepX = (ex - sx) / (breaks + 1);
                float stepY = (ey - sy) / (breaks + 1);

                for (int q = breaks; q >= 0; q--) {
                    pointlist[writePos - 2] = sx + (stepX * q);
                    pointlist[writePos - 1] = sy + (stepY * q);
                    writePos -= 2;
                }
            } else {
                pointlist[writePos - 2] = sx;
                pointlist[writePos - 1] = sy;
                writePos -= 2;
            }
            ex = sx;
            ey = sy;
        }
        count = splitCount;
        if (relativeIndex == 0) return 0;
        return returnIndex;
    }


It has a lot of speed-based fanciness. Some of which looks weird but is totally required if you wanted to do something extra fancy. Some of which simply added fancy, but not speed, given that I never used it or other fixes negated it.
