### ISSUE TITLE
IFormat.Reader signature is too specified.

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#41]
While the EmbPattern class has the right stuff to work like that it should actually be nearly identical to IFormat.Writer as:

```
  public interface Reader {
        void read(EmbPattern pattern, InputStream stream);
  }
```

The reader interface is firstly required to create the pattern object internally to the reader. This means you can't load up two different designs into the same pattern, or many other things. And it requires a DataInputStream, which is fine to wrap the inputstream into but isn't needed for XML which basically would only require InputStream to be passed to the SAXParser, and the run through the handler.

**Comment by JoshVarga** [comment]
I agree, I thought about about a while ago but haven't had the focus to clean it up. This is updated in the most recent commit.
