### ISSUE TITLE
Add a default color

### ISSUE THREAD

**Issue by valonsejdini** [Embroidermodder/MobileViewer#48]
When the design is loaded there should be default colours applied to the design as opposed to random colouring.

**Comment by tatarize** [comment]
Any preference on a pallette? 

I solved for a few of them for maximally distinct colors color palettes back in the day. But, they start to clash at about 30 regardless and aren't great for visually impaired people and you're better off with other criteria to differentiate one thing from the next. 

https://stackoverflow.com/questions/309149/generate-distinctly-different-rgb-colors-in-graphs/12224359#12224359

I also solved for the naive rgb iterations, but the results are horrible even though you can get all 16,777,216 colors like that:

![colordistribution](https://user-images.githubusercontent.com/3302478/33870251-d85a198e-dec1-11e7-9d77-ea2173b5d16a.png)

So I'm thinking pick any 30 reasonable colors and go random after that, so:

        "#000000", "#FFFF00", "#1CE6FF", "#FF34FF", "#FF4A46", "#008941", "#006FA6", "#A30059",
        "#FFDBE5", "#7A4900", "#0000A6", "#63FFAC", "#B79762", "#004D43", "#8FB0FF", "#997D87",
        "#5A0007", "#809693", "#FEFFE6", "#1B4400", "#4FC601", "#3B5DFF", "#4A3B53", "#FF2F80",
        "#61615A", "#BA0900", "#6B7900", "#00C2A0", "#FFAA92", "#FF90C9", "#B903AA", "#D16100"

**Comment by tatarize** [comment]
https://github.com/Embroidermodder/MobileViewer/pull/79

**Comment by tatarize** [comment]
Just used the PEC colors, they were a command away.
