### ISSUE TITLE
.DST sequins? Does anybody know the command for that?

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#58]
Google Play Review:  jignesh thakore  "view sequins and original thread look Hi, it's a good app. Plz add an option to view sequins in dst file, also total stitches and total sequins and also original thread look in app."

He's right about the sequin thing they do exist apparently in .DST files. And it wouldn't be impossible to draw a sequin circle at the proper position etc, but what command is that? Implementation would consist of a pointlist of sequin locations and just iterate that list and add a set shape for sequins.

**Comment by tatarize** [comment]
Had my brother use EO to make a few sequin files, it's some eject command, but I haven't gotten around to firing up my hexeditor. 
[Sequin.zip](https://github.com/Embroidermodder/MobileViewer/files/1308662/Sequin.zip)

**Comment by wwderw** [comment]
In Wilcom, they do a sequin on (engaging the dispenser) and a drop sequin for actually release the sequin.  I don't know what it is for a dual sequin dispenser, I don't use that option as I only have the one dispenser and I have to use a stop code to make any changed to it (different shape sequin, color etc).

Not all sequins are circles and then you have different sizes as well.  You would also have to use the correct stitch work to "tack down" the appropriate sequin.  I do believe the typical one, at least the typical one that I use, is 5mm.

**Comment by tatarize** [comment]
The code for turning on sequin is 0, 0, 0b01000011 in the dst. Then jumps eject the sequin.

**Comment by wwderw** [comment]
> Then jumps eject the sequin.

In another project (Ink/Stitch), we were able to parse that much out looking at the CSV.  Took awhile for that.

>The code for turning on sequin is 0, 0, 0b01000011 in the dst.

I don't think we were ever able to figure that out.  At least, I don't recall it being mentioned anywhere, but that in of itself, doesn't mean that it wasn't.

**Comment by tatarize** [comment]
I was checking the issues on InkStitch and it referenced that. So I bothered to process some of the sequin generation files I've had to figure out the commands. Rewrote the parsing to make sure I could find the unknown elements and found what the sequin command looked like to post it as a reply to that issue.

There's a bunch of issues with sequins the way he's doing that, but it's at least something we should know about. There's not an obvious way to hack in a stitch with some sequins into svgs. You could certainly have a bunch of linesegments but a different specific command like "SLOW" or "SEQUIN" isn't something that could be marked up within that format, at least not seamlessly.

**Comment by wwderw** [comment]
> but a different specific command like **"SLOW"** or "SEQUIN" isn't something that could be marked up within that format, at least not seamlessly.

Well, within a DST, to my knowledge "SLOW" (or "FAST") isn't supported at all.  The only format that I'm aware of that supports it is the U?? file for Barudans (for both commands).

**Comment by tatarize** [comment]
Yeah, but if you wanted that in the native design and exported it to just those formats that had them. You'd need to be able to flag every stitch with those commands or any command that might exist. Adn you couldn't really do that without being able to markup the stitch data at the stitch level, this is not something svg is great at.
