### ISSUE TITLE
Onerous new license?

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#63]
What's with switching to a GPL derivative? While I saw there were some sketchy things in the app store that were just outright rip offs. But, this would generally mean for me that any contributions I make can only be one sided. I can add code into MobileViewer but not use any from it.

So even if I went and switched the general file input/output scheme to one that fixes most of the objections I've had with it:

* ability to stop loading mid process (quite critical for thumbnail viewer)
* the relative/abstract commands (implementing svg path V command is impossible because it means move to exactly this y and the same relative x as before)
* how it builds the stack of stitch blocks.
* using the EmbPattern too directly with rather excessive coupling.
* The lack of a good patterning out loop requiring, means it needs too much proprietary accessing of the pattern.
* Other file reading tools and functions (eg. file writing needs a stream stack, file reading needs to track the position of the writing). 

And this allowed for some very nice libembroidery like Embroidery IO for a java agnostic platform, I couldn't turn around and use the file formats coded in that scheme without releasing my source code.

**Comment by JoshVarga** [comment]
I'm open to suggestions. 
You are correct that this is a reaction to the blatant rip offs. 
The app was pulled from the app store from some complaint, after reviewing who could be complaining I found a few direct copies of the app.
They are already in violation of the previous license anyway but I did not intend to put the code out there so that some pseudo-developer could just slap ads on it and call it a day.

Let me know which license you think would work best for you, while still aiming to prevent total ripoffs.

**Comment by tatarize** [comment]
With the GPL. You could simply publish your modified code. Here's the code I took from this project and here's the ad I added to the source. The point is they did zero work publishing that zero work would not prevent them from doing anything. And they really might not care anyway.

But, this certainly prevents me from doing anything. My project is rather extensive to the point that I've currently been working on adding in geometric shapes and fills (after working out the flaws in the underlying math used by most embroidery programs) but I looked at the 20+ different embroidery formats and saw more the inherent disfunction of the industry and just implemented .dst and .svg (I was still under the sort of flawed vector art view that is also disfunctional in the industry). 

But, then I ran into this product and you were cross coding some of the libembroidery stuff which was awesome. And contributed stuff to make the project successful. And gained the ability to load and save some formats I hadn't done any heavy work on, which seemed like a solid trade off. 

I really don't know what could prevent such blatant ripoffs. I am not remotely sure they don't convert and post different apps with new logos, names and ads to the play store all day long, completely ignoring the licensing. So the simple existence of the source online would be the main reason.

I had planned on adding my more robust IO stuff and asking some save formats like .xxx and .vp3, and I know this licensing would certainly prevent that. Though I haven't even gotten around to fixing the .svg #888 color bug. I don't really have a solution to the ripoff issue. I even noted a ripoff comments of one of them on Play. And on the machine embroidery wiki which I asked to join because it was one of the most helpful resources on machine embroidery ( http://edutechwiki.unige.ch/en/Computerized_embroidery ).

**Comment by JoshVarga** [comment]
I have switched the license back to MIT. The people that just rip-off the code with no benefit to the end-user are very irritating. Google has been very responsive to the complaints against "copy cat" applications, multiple applications were recently removed from the App Store. Those applications added no value to the end-user, only ads etc. I feel better now about continuing with the license as-is (MIT)

**Comment by tatarize** [comment]
Exclude that on the license. Full commercial and public use of the code, without attribution, except for putting the app up on google playstore or other app marketplaces with no substantive changes other than advertisements.
