### ISSUE TITLE
Get Flipped,Centered,PositiveCoords Pattern shouldn't create a new object.

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#8]
It's just easier and less weird to just move the relevant points around, within the object you already have, rather than creating a new one. For example, (if using my new core) the Positive Coords function should be:
```
    public Pattern getPositiveCoordinatePattern() {
        int moveLeft, moveTop;
        EmbRect boundingRect = this.calculateBoundingBox();
        moveLeft = (int) boundingRect.left;
        moveTop = (int) boundingRect.top;
        Matrix m = new Matrix();
        m.setTranslate(moveLeft,moveTop);
        for (StitchBlock sb : this.getStitchBlocks()) {
            sb.transform(m);
        }
        return this;
    }
```

**Comment by JoshVarga** [comment]
Thanks, I agree, that will be a big help. Thanks for your other contributions as well.

**Comment by tatarize** [comment]
Yeah, it's not super obvious but I've written the only actual embroidery software for android. And I tested basically every single way to get the best performance out of Android and keeping the relevant data stored in an array of floats and feed it to the GPU is by far the best. You didn't have anything that redrew the screen but it was basically going to be impossible.

 ([Touch Embroidery Free](https://play.google.com/store/apps/details?id=com.photoembroidery.tat.touchembroideryfree)).

It also fits really well with using the Matrix class so those functions can be simply converted to easy things like:

```
    public Pattern getFlippedPattern(boolean horizontal, boolean vertical) {
        double xMultiplier = horizontal ? -1.0 : 1.0;
        double yMultiplier = vertical ? -1.0 : 1.0;
        Matrix m = new Matrix();
        m.postScale((float)xMultiplier,(float)yMultiplier);
        for (StitchBlock sb : this.getStitchBlocks()) {
            sb.transform(m);
        }
        return this;
    }
```

Because most of the time you'll just be doing some kind of affine transformation. 

It's also not obvious but, the way I did the viewMatrix and invertMatrix is also the best way to do that. Generally it's a far cry from having all the pan, scale, rotate operations setup. But, given that viewMatrix you can simply move change it, and invalidate() the view, and recalculate the invertMatrix  (so that screen touches can be transformed from view coords to scene coords) and it'll look properly like you have an infinite canvas.

Tried to give you a pretty solid leg up.
