### ISSUE TITLE
Name? MobileViewer EmbroideryViewer

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#85]
It's not that critical but is there an official name of the project. Obviously the Google Play thing is set, the name is Embroidery Viewer and the package name is locked in for existing on the playstore. But, which name is it? Or did a couple name choices get half-locked in place?

**Comment by JoshVarga** [comment]
I am OK with any name, I will need to change it on the next publish since
the publishing key has been lost.

It will need to be a new app so will result in a new name.

I am open to suggestions.

**Comment by tatarize** [comment]
Embroidermodder MobileViewer

Might as well capitalize on some of the brand or whatnot.

**Comment by tatarize** [comment]
Name was not changed. 
https://play.google.com/store/apps/details?id=com.embroidermodder.android
