### ISSUE TITLE
PCS and JEF may be somewhat unstable.

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#87]
In #86 I updated to the best versions I had and worked through them all for Touch Embroidery so they should work better than other previous versions. At issue though, are that Wilcom makes .pcs files with some stuff at the end which isn't read or written. See the .pcs reader/debugger I have at:

https://jsfiddle.net/sL8z1vmh/

It parses like Embroidermodder parsing but has some extra stuff at the end that is unknown but made by all qualified generators.

I haven't checked with an owner after the 0x0A -> 0x14 change but I was told by a user that the JEF files didn't load on the machine.

---

I restructured the directories to be way more coherent. It needs a couple tweaks and fixes but most of these are pretty minor.

* Statistics needs to work again.
* The embroidery viewer is offline due to changes.
* JEF write issue.
* PCS write issue.

**Comment by tatarize** [comment]
I rewrote most of LibEmbroidery with a bunch of my middle level fixes for meshing all embroidery formats together in python for [pyembroidery](https://github.com/EmbroidePy/pyembroidery) including fixing the .jef files. So whatever the issue is in the writer, I should fix them when I more or less port the formats over from that.

**Comment by JoshVarga** [comment]
I was thinking of pushing a new version to the app store soon and was going to do a bit of testing. Do you know of anything that you would like to add? Possibly the changes you mentioned?

**Comment by tatarize** [comment]
I've been, over the last few days, porting the pyembroidery stuff over to Java. And busily testing it.  It should, in theory, do a solidly proper job using the bit of major advancements I made with pyembroidery over to the java version. Generally the primary idea is a pretty advanced pre-processing system that will take a very wide and inconsistent set of potential embroidery commands and convert them into something which should be consistent for any particular writer while minimizing data loss.

I also had to rework a lot of the formats and make sure they were consistent. Properly dealing with sequin commands, stop commands, and needle change commands.  And I focused a bit on making sure the readers and writers were styled such that you could easily debug and understand them. --- I figured since I wrote that stuff I could port it back to Java.

I'm also trying to maintain the encapsulation. I have a several projects that run on java, and I'd really like to drop the source files on to any of them and just have it work right out of the box. I wrote pyembroidery as basically a drop in pure-python replacement for lib-embroidery for inkstitch, and any other embroidery project people might have in mind. But, since I had to rewrite everything basically from scratch, I also rethought things like the commands structure and how it should deal varied things like converting from a format with sequins to one without. And dealing with things like subdividing long stitches outside of the writer, or using a jump stitch to make that long stitch without using stitches, and making it all able to be set in a consistent way.

And made sure to consistently update the edutech wiki ( https://edutechwiki.unige.ch/en/Embroidery_format ) on the formats as I went through them, hopefully helping to fix the documentation issues with formats. The biggest issue out of lib-embroidery is that compounding write error if you use floating point numbers. But, the inkstitch folks ran into several other sort of unstable things there. (And oddly enough stuff like .hus and .vip seem kind of hopeless. I hear it's like a small table arc compression or something but I dunno where libembroidery got that code looks decompiled but it's utterly unportable.)

My port isn't finished yet, but I'll try to hook the bits I'm currently working on back into MobileViewer (or whatever name you've settled on), so you can review the code. The pyembroidery stuff is stable so any little bugs must be a minor error or a bug in a section I had to rewrite. But, there's currently a few I'm playing whack-a-mole with. If I did everything right it should just work to copy the stuff across and hook it up.

**Comment by tatarize** [comment]
It looks a bit hamfisted currently. Because it still uses the older heavily coupled version and I dropped in the less coupled version too. So it weirdly needs to convert from the old code to the new code while using both. But, it's likely a much better way of doing that. 

As for things that more properly need to get done, there are a lot of different commands that are not actually hooked to much of anything. Like it has a couple ways of exporting stuff but it doesn't really use them. And there's some things that aren't very hooked to anything. Like there's no real distinction between "Open File" and "Load File" but they do different stuff that isn't actually setup in any cogent manner.  Hopefully the drop in EmbroideryIO stuff works. Properly the stuff that is left could be coupled more closely, as it's not trying to play double duty as the loading datastructure and the datastructure being actively used.

**Comment by tatarize** [comment]
And it still likely has a couple basic format bugs (exp output is funky for example), but I'll work on that more, and need it for my own uses. So those changes would just update those sections of code rather than the other bits. So in theory everything outside of EmbroideryIO is the same general not very highly tinkered with UI stuff. And everything else could be checked and tinkered with.

I was just making sure this project could be successful wherever it went, but didn't really care much where it was going.  So the real deficits are in the UI, not the panning zooming bits, but everything else. There's really no stated idea of where it should go or what it should do. Should it load every format and share out a bunch more? Should it use instant apps to let people load embroideries on their phone through a seamless transition on a website? Should it be a sort of converter thing? Should it duplicate the viewing and saving functionalities of Embroidermodder 1.7?

**Comment by tatarize** [comment]
Okay, that update should fix it, or at least the JEF file format. PCS might still be fubar and doesn't seem to work. But, I don't think it's mapped out enough to know. But, the formatting will also do things like load and save sequins in files even though there's no actual mapping for how that would work inside the app, it works inside EmbroideryIO.
