### ISSUE TITLE
Pushing a New Version to the app store

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/MobileViewer#90]
* Proper name #85 "Embroidermodder Mobile"?
* Menu: Open File. Works. Loads recent, but if you select a proper embroidery file, it loads.
* Menu: Statistics. Fails. Loads dialog, but displays nothing.
* Menu: Share. Works. Displays list of formats to exports.
    * .cvs should be csv.
    * displays disabled unavailable formats. These are not included but might be distractive.
* Menu: Load File. Fails. Loads dialog, but displays nothing.
    * This is thumbnail viewer.
    * "Load File" and "Open File" are synonymous names for different function.

* Drawer: works.
    * This displays giant, and seemingly unhelpful recycler view of "stitch x, y" for thousands of stitches.

**Comment by tatarize** [comment]
Drawer:
Displays
* Metadata
* Threads
* Stitches.

The problem with the threads is if it had no threads to start, it doesn't force them to add as random. Loading something like a .dst file gives no thread colors, so it doesn't have them. Loading something like a .jef or .pes it has a color and can be changed accordingly with that view.

**Comment by tatarize** [comment]
Fixed Statistics.

Upgraded thumbnail viewer to newer version that I made for TE. Can certainly be made significantly better but this is better than what was there, and actually works.

**Comment by tatarize** [comment]
Fixed csv spelling error. Fixed menu name for "Load File" -> "Folder". 
Changed app name to simply "Embroidermodder"

**Comment by tatarize** [comment]
Autofixed the colors on load, tweaked the fragment close order.

**Comment by tatarize** [comment]
@JoshVarga Okay. That should be it for the stuff that needed updating or seemed wrong. Not adding more features but I hooked all the parts up. So any tweaks you wanna make are good and I shouldn't end up second guessing them or changing something.

There's a couple strings that aren't translated. But, I don't speak those languages so I can't fix them. And a couple moved not-deleted files (but those will be dropped anyway so it's not like that cleaning is actually helpful). 

I'm also good with just sending that version.

**Comment by tatarize** [comment]
Did this hit a snag or something?

**Comment by tatarize** [comment]
@JoshVarga you did something again. This is still kinda neglected. I've updated Embroidepy/pyembroidery and am planning on a similar update to EmbroideryIO. Which does some stuff like Jef trims and DST trims and PES stops. And am still curious as to your position on including it as a library vs. directly imbedding the the project.

**Comment by JoshVarga** [comment]
I think it would be best to move forward with using EmbroideryIO as a library, so that we don't need to make updates in multiple spots. Getting out of sync gets really nasty. I imagine if there are any significant updates that I need to make you would be open to pull requests. If not we can always embed it again on this project.

**Comment by tatarize** [comment]
The version here should be what I figured was solid enough for release last year..

The only thing I've done recently for pyembroidery is add a merge pattern method, a bunch of python specific dunder methods, and adding in trim and stop interpolations into jef, dst and pec/pes. And likely will have to port some of those changes into EmbroideryIO. I'm also mulling around adding in the color-file formats. So .EDR and .COL and .INI and then I could use the same STOP interpolation routine I specifically used for PES/PEC for things like .DST. If it loads the EDR and has a double color to the same color, it would make that a stop in the loaded DST rather than color change. The same could hold true for things like DST with an extended header, as that DST modification does include give it threads and those could duplicate. --- But these are all pretty rare edge conditions now.

I'll toss in an invite for you on EmbroidePy. The packaging for EmbroideryIO android and jvm is just done through jitpack so it only requires updating the master branch and adding a release version. Which is pretty nice. I use it in a different private JVM package as well, and as part of TouchEmbroidery. If everything else failed it could just be forked to Embroidermodder and the jitpack bit would work the same but just reference Embroidermodder rather than EmbroidePy.

**Comment by tatarize** [comment]
A version was pushed.
