### ISSUE TITLE
error writing jef not open on machines

### ISSUE THREAD

**Issue by fabricocouto** [Embroidermodder/MobileViewer#96]
case COLOR_CHANGE:
                    point_count += 2;
                    colorsalto++; // add
                    continue;
                case END:
                    break;
            }
        }
        writeInt32LE(point_count+colorsalto);// calc

there is an error writing the jef file
in point count i had to add more because it was missing more jumps so with this added here it was perfect with the wilcom program but at the end of the binary file it is saving more points

so what I looked at and buying other files would be like jump or trim / 2
![Sem título](https://user-images.githubusercontent.com/20323161/67500944-d0603900-f659-11e9-89a0-fa6ca7c24a11.png)

**Comment by tatarize** [comment]
I had intended to check this but, I think it might be the JEF trims. I had intended to run down the trimming data and see what it does to the count, but I neglected to check or highly investigate it, especially after learning it sewed anyway.

**Comment by tatarize** [comment]
Unless you just mean the extra data at the file end. That was not found in all output and the sewing worked fine so it was omitted. Sometimes later versions add stuff and that stuff isn't really needed and might mess with compatibility. Or might just do something else that isn't needed when I can easily remain compatible with all the other versions.

**Comment by fabricocouto** [comment]
I have a janome machine that reads the jef file.
saw errors converting from dst to jef
pes all versions pes for Jef
Jef also to Jephthah
and exp for jef
of the converts to jeft were opened i look at two errors in the binaries that manually modified the files were opened in the machine.
amount of points
is the end of the binary in wrong possibilities 0x80 and 0x10

**Comment by tatarize** [comment]
If I am understanding correctly, regardless whether it runs on your machine or the actual embroidery machine is giving you actual error warning feedbacks? Specifically complaining about the end of file and the number of commands given?

Or am I misunderstanding? There's certainly a chance I messed up the count for the JEF format especially with trim commands. (Though I think I neglected to update those here). I previously mapped the file count bit based on other commands and I wasn't sure how those messed with the count. But, reports came back that they sewed so I didn't worry too much about them.

The extra elements on the Wilcom export was not found on all elements and some of Janome's own software omitted them so they were omitted.

Where are you seeing errors? Is your machine actually telling you this stuff?

---

There's also some chance that some written elements have been corrected but not reflected here.

The main branch of Embroidery IO was updated in May. Whereas here it was November of 2018. This would have been before JEF Trims 0.0.2 was added. And I recently heard back from Josh about stripping the EmbroideryIO here and using it as a plug-in. So there's some JEF changes that aren't found here.

I stopped messing with stuff here after I told Josh that I would get it to a releasable version. I did that and held off messing anything else up. However, that also included freezing the EmbroideryIO version here since those changes could be breaking changes. But, I continued to port over some changes in the main branch. And some corrections to JEF came down through pyembroidery which were then ported over from that.

So pyembroidery has all the most up-to-date changes. Written in python. Updated 3 days ago for a python bug.
Embroidepy/EmbroideryIO has the most recent EmbroideryIO changes updated May 2019.
Embedded EmbroideryIO has an old version updated Nov. 2018. 

I got feedback here to go ahead and remove the embedded version here. Basically the code base will be deleted and the build gradle will get the line to use Embroidepy/EmbroideryIO:
`    implementation 'com.github.EmbroidePy.EmbroideryIO:embroideryio-android:0.0.9'`

Lemme try updating that in a branch. And see if it works out of the box.

**Comment by fabricocouto** [comment]
I don't understand very well why the machine doesn't recognize the file being something so inferior but this bug is old, I passed it to josh for years in embroiderrmoder where we fixed it embroiderymodder until then I didn't write jef, I think maybe it's not writing jef but  yes reading the other  files like trim and jump are being stored
I test py too but the same with the same bug

**Comment by tatarize** [comment]
If it doesn't work in the python version then it is simply a format bug. Do Wilcom files trigger the error? And if you edited a file from one pyembroidery produces to one without the error what would that be? Could you make such a file and show me the difference?

`binaryWriteInt(file, embStitchList_count(pattern->stitchList) + max(0, (6 - colorlistSize) * 2) + 1);`

Is the code in libembroidery. The code in pyembroidery is:

    point_count = 1  # 1 command for END statement
    for stitch in pattern.stitches:
        data = stitch[2] & COMMAND_MASK
        if data == STITCH:
            point_count += 1
        elif data == JUMP:
            point_count += 2
        elif data == TRIM:
            if trims:
                point_count += (2 * command_count_max)
        elif data == COLOR_CHANGE:
            point_count += 2
        elif data == END:
            break

This would add 1 for each command element and `(6 - colorlistSize) + 1`. So 1 = 6, 2 = 5, 3 = 4... etc. I'm not actually sure what that bit of addendum is for but I don't think I saw it elsewhere.

**Comment by fabricocouto** [comment]
save 2 files converted to jef in python and at andoid and send me at fabriciocoutodivino@gmail.com
I will open in the binary and open in the machines

**Comment by tatarize** [comment]
[fishjefs.zip](https://github.com/Embroidermodder/MobileViewer/files/3783391/fishjefs.zip)

**Comment by tatarize** [comment]
@fabricocouto Hm. Looking at the code you sent:

https://github.com/EmbroidePy/EmbroideryIO/pull/13/commits/1e802bf2669fb13ad6fffe0381cf78b1aa7707f5

I at least see what you were saying about the counting of the various elements and cutting it in half. But, since all the elements it's given are 2 or 4, and you divide it in half. Why would that at all be different from the 1 or 2 but not divided in half. There's an issue with STOP though it shouldn't be given that command. It's clearly back to a form it used to be in, but I don't see what's changing to make one of them work or another fail.

**Comment by fabricocouto** [comment]
I know it sounds weird and quite out of the ordinary but believe me I tested a lot a lot and if I don't write this way the files won't open on the machines


for (int i = 0, ie = stitches.size(); i < ie; i++) {
            int data = stitches.getData(i) & COMMAND_MASK;
            float xe = stitches.getX(i);
            float ye = stitches.getY(i);

            switch (data) {
                case STITCH:
                    point_count += 1;
                    point_count += 1;
                    continue;
                case STOP:
                case COLOR_CHANGE:
                    point_count += 1;
                    point_count += 1;
                    point_count += 1;
                    point_count += 1;
                    continue;
                case JUMP:
                    point_count += 1;
                    point_count += 1;
                    point_count += 1;
                    point_count += 1;
                    continue;
                case TRIM:
                    if (trims) {
                        point_count += 1;
                        point_count += 1;
                        point_count += 1;
                        point_count += 1;
                    }
                    continue;
                case END:
                    break;
            }
            break;
        }
        point_count += 1;
        point_count += 1;


pointcount =point_count/2;

**Comment by tatarize** [comment]
I'm pretty sure that's basically what the embroidermodder code was before I modified it. The thing is I can't actually see any difference. By definition that's 1 for every stitch, 2 for color changes and stops, 2 for jumps, and 2 for trims. And the 1 command for the end command. Then foregoing the point_count. should be identical to what I'm doing now. If you add half as much and you add them as whole numbers and you don't divide the count in half. That's the same thing.

I'll check run a test on it and make sure there's not some other change I'm not seeing but from my view the math should be identical.

**Comment by fabricocouto** [comment]
test this the way I sent it and send me the file here for me to open

**Comment by tatarize** [comment]
[2versions.zip](https://github.com/Embroidermodder/MobileViewer/files/3796069/2versions.zip)

Okay, `current` is the way I have it. `Fab` is the way your code had it.

**Comment by tatarize** [comment]
![fab](https://user-images.githubusercontent.com/3302478/67991417-5fd79000-fbf6-11e9-81bc-b9414828efdd.png)

Outside of the data-time there is a difference that looks to be the count there. So there may well be something to that.

**Comment by tatarize** [comment]
int point_count = 1; // 1 command for END;
        for (int i = 0, ie = stitches.size(); i < ie; i++) {
            int data = stitches.getData(i) & COMMAND_MASK;
            switch (data) {
                case STITCH:
                    point_count += 1;
                    continue;
                case STOP:
                case COLOR_CHANGE:
                    point_count += 2;
                    continue;
                case JUMP:
                    point_count += 2;
                    continue;
                case TRIM:
                    if (trims) {
                        point_count += 2;
                    }
                    continue;
                case END:
                    break;
            }
            break;
        }
        writeInt32LE(point_count);

This code ends up being the same but the count is different with my code and this code. Maybe it's just the accounting for stops or something, but that doesn't make much sense.

**Comment by tatarize** [comment]
Your code.
        
        int pc0 = 1; // 1 command for END;
        for (int i = 0, ie = stitches.size(); i < ie; i++) {
            int data = stitches.getData(i) & COMMAND_MASK;
            switch (data) {
                case STITCH:
                    pc0 += 1;
                    continue;
                case STOP:
                case COLOR_CHANGE:
                    pc0 += 2;
                    continue;
                case JUMP:
                    pc0 += 2;
                    continue;
                case TRIM:
                    if (trims) {
                        pc0 += 2;
                    }
                    continue;
                case END:
                    break;
            }
            break;
        }
        writeInt32LE(pc0);
 
Vs.
Current code.

        int pc1 = 1; // 1 command for END;
        for (int i = 0, ie = stitches.size(); i < ie; i++) {
            int data = stitches.getData(i) % COMMAND_MASK;
            switch (data) {
                case STITCH:
                    pc1 += 1;
                    continue;
                case JUMP:
                    pc1 += 2;
                    continue;
                case TRIM:
                    if (trims) {
                        pc1 += 2;
                    }
                    continue;
                case COLOR_CHANGE:
                    pc1 += 2;
                    continue;
                case END:
                    break;
            }
        }
        writeInt32LE(pc1);

**Comment by fabricocouto** [comment]
this calculation is very simple to understand
the start of the dot 0x80 and the end of the dot 0x10 is exactly the calculation you need the dots if you could add the dots at the end to write the bite would be easier

but in this case it has to be two loops one for the point and one to write the point
![Sem título](https://user-images.githubusercontent.com/20323161/67992051-19942800-fc1a-11e9-805a-2a7648135b6b.png)

**Comment by fabricocouto** [comment]
![image](https://user-images.githubusercontent.com/20323161/67992174-7e4f8280-fc1a-11e9-8283-20e3f51a25ab.png)
butterfly-fab.jef open correct

**Comment by tatarize** [comment]
I added the STOP to it, still giving me BE rather the C9. Yeah, I've got no qualms with the understand that you're right. I just can't find where the difference could possibly be.  It's off by 11 for some reason. I guess the code says the same thing now, but I dunno why it's off by 11 and it's sure to be something small.

**Comment by fabricocouto** [comment]
saw that this stranger puts you in sequence
+1
+1
+1
+1

  and divide by 2 the result is different

**Comment by tatarize** [comment]
I'll just use your loop. It looks like the actual difference is that your code uses two breaks. Though that shouldn't actually mess things up I wouldn't think. But, apparently.

**Comment by tatarize** [comment]
https://github.com/EmbroidePy/EmbroideryIO/releases/tag/0.1.10

Okay, the update here where it gets the version of EmbroideryIO will just need moving up to .1.10 to fix. I'm pretty sure it's the break. The copying of the code gave it the same count. It just needs to do the same count for both or I could just write it and then fill in the values. But, I went with the simplified form of your loop that worked. I'll try to figure out the specific error to see if it also exists in pyembroidery. But that should fix it.

**Comment by fabricocouto** [comment]
okok
Take a look at the preview topic that opens, see what we can do to make a simple degrade to improve the change.

**Comment by tatarize** [comment]
Hm. It's actually not the break. Added it to your version of the code and it *still* gave C8. That's starting to annoy me.

**Comment by tatarize** [comment]
int data = stitches.getData(i) % COMMAND_MASK;

The bug is `%` where `&` should be used. The color changes have extra info that makes them no longer equal which causes them to not count. Yay! Found it!

**Comment by fabricocouto** [comment]
c8 for this file that was not saved by wilcom is correct the exact calculation of bytes and dots
if you save by wilcom you will get a 9B because it corrects the center of the drawing

![image](https://user-images.githubusercontent.com/20323161/67993579-2f0c5080-fc20-11e9-9650-f4c28d109493.png)

**Comment by fabricocouto** [comment]
congratulations

**Comment by fabricocouto** [comment]
but I believe it will still give the error because the code here is like this with & yet it was giving the error

**Comment by tatarize** [comment]
Nah, Wilcom likely added some stitches somewhere. The outputs are always a bit different. Like deleted a tiny stitch or broke a long one. It tends to do that.

**Comment by tatarize** [comment]
I also made a wilcom file. The number for the count there is the number of words in the actual stitches block. With 2 byte words. Wilcom's different number is also met by different stitches but is spot on.

My count was wrong because of the `%` bug. It should be fixed now.

**Comment by tatarize** [comment]
https://github.com/Embroidermodder/MobileViewer/commit/8103a588d83e8066d3f4b9897a98ad22599b0869 should have this fixed.
